export { default as HomePage } from './HomePage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as PokemonPage } from './PokemonPage'
export { default as AboutPage } from './AboutPage'
export { default as RandomPage } from './RandomPage'
